version: '3'

services:
  php:
    build:
      context: ./docker/php
    container_name: [votre_prenom]_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network
      
  mysql:
    image: mysql:8.0
    container_name: Naylis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Naylis_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    
volumes:
  mysql_data:
